### PR TITLE
Array support

### LINKED ISSUE #69: Would you be open to support array types?
I have added in a case to handle array type because I need to deal with `uuid.UUID` type

```
	var err error
	dataKind := getKind(val)
	fmt.Println(name, val, dataKind)
	switch dataKind {
	case reflect.Bool:
		err = d.decodeBool(name, data, val)
	case reflect.Interface:
		err = d.decodeBasic(name, data, val)
	case reflect.String:
		err = d.decodeString(name, data, val)
	case reflect.Int:
		err = d.decodeInt(name, data, val)
	case reflect.Uint:
		err = d.decodeUint(name, data, val)
	case reflect.Float32:
		err = d.decodeFloat(name, data, val)
	case reflect.Struct:
		err = d.decodeStruct(name, data, val)
	case reflect.Map:
		err = d.decodeMap(name, data, val)
	case reflect.Ptr:
		err = d.decodePtr(name, data, val)
	case reflect.Slice:
		err = d.decodeSlice(name, data, val)
	case reflect.Array: // required to handle uuid.UUID type
		err = d.decodeArray(name, data, val)
	default:
		// If we reached this point then we weren't able to decode it
		return fmt.Errorf("%s: unsupported type: %s", name, dataKind)
	}
```

Would you accept this new feature?

### PR DESCRIPTION
**Pull request by rvolosatovs**
Closes #69

### CODE REVIEW

**Comment by Linuturk** [comment]
Wanted to :+1: this. Tested by pinning to @rvolosatovs branch and repo and it solved my problem using `gocql.UUID` types.

**Comment by Linuturk** [comment]
@rvolosatovs Curious why this was closed?

**Comment by rvolosatovs** [comment]
Deleted the branch, as it's merged in `master` of the fork and forgot, that it would also close the PR.

**Comment by rvolosatovs** [comment]
@mitchellh rebased on top of the latest `master`, would you mind taking a look?

**Comment by caledhwa** [comment]
Can we get this merged @mitchellh ???

**Comment by mitchellh** [comment]
Thanks @rvolosatovs!

**Pull request merged**
