### PR TITLE
Fix data race in decodeStruct

### PR DESCRIPTION
**Pull request by magiconair**
Using `*reflect.StructField` as map key results in a data race. I honestly
do not understand why yet and can only reproduce this in the consul
codebase with high concurrency but this patch fixes it.

The same problem also exists in hashicorp/hcl.

https://github.com/hashicorp/hcl/pull/213

### CODE REVIEW

**Comment by danielchatfield** [comment]
@magiconair Did you ever get to the bottom of how this data race can occur?

We've experienced this in production and I can't work out (barring bugs in the Go runtime) how this could cause a race. I've updated this dependency within our codebase but it is somewhat unsatisfying to not know why.

**Comment by magiconair** [comment]
@danielchatfield no idea unfortunately.

**Comment by jackkleeman** [comment]
@magiconair do you have any repro code?

**Comment by magiconair** [comment]
I think what I did was to run `go test -parallel 128 -race`

**Comment by jackkleeman** [comment]
Ok thanks!

**Comment by jackkleeman** [comment]
@magiconair were you able to reliably reproduce? We are not able to. In production at one time we had the race repeatedly, but now we can't reproduce there either. We can't figure out what might be changing from one day to the next.

**Pull request merged**
