### PR TITLE
Added decoder option for squashing embedded structs

### LINKED ISSUE #42: Squash embedded structs by default
To be consistent with "encoding/json", an embedded struct like

```
type Outer struct {
    Inner
}
```

should behave as though tagged with `mapstructure:",squash"`, unless explicitly given a name like `mapstructure:"Inner"`.

Example code demonstrating the inconsistency with "encoding/json":

```
package main

import (
    "encoding/json"
    "fmt"
    "github.com/mitchellh/mapstructure"
)

type Inner struct {
    Name string
}

type Outer struct {
    Inner // works if you add `mapstructure:",squash"`
}

func main() {
    input := Outer{Inner: Inner{Name: "mitchellh"}}
    fmt.Printf("input: %#v\n", input)

    bytes, err := json.Marshal(input)
    if err != nil { panic(err) }
    fmt.Printf("json: %v\n", string(bytes))

    var outputGood Outer
    err = json.Unmarshal(bytes, &outputGood)
    if err != nil { panic(err) }
    fmt.Printf("outputGood: %#v\n", outputGood)

    var tmp interface{}
    err = json.Unmarshal(bytes, &tmp)
    if err != nil { panic(err) }
    fmt.Printf("tmp: %#v\n", tmp)

    var outputBad Outer
    err = mapstructure.Decode(tmp, &outputBad)
    if err != nil { panic(err) }
    fmt.Printf("outputBad: %#v\n", outputBad)
}
```

The output is:

```
input: main.Outer{Inner:main.Inner{Name:"mitchellh"}}
json: {"Name":"mitchellh"}
outputGood: main.Outer{Inner:main.Inner{Name:"mitchellh"}}
tmp: map[string]interface {}{"Name":"mitchellh"}
outputBad: main.Outer{Inner:main.Inner{Name:""}}
```

The correct output would have:

```
outputBad: main.Outer{Inner:main.Inner{Name:"mitchellh"}}
```

### PR DESCRIPTION
**Pull request by bminer**
Fixes #42

### CODE REVIEW

**Comment by bminer** [comment]
@mitchellh - Mitchell, please let me know what you think about this patch.  I'm willing to clean things up where needed.  Also, if you need help maintaining this lib, I would be happy to contribute where possible.  Thanks!

**Comment by bminer** [comment]
I'm hoping we can merge this soon?  I feel like it's a simple change and complete with tests.  Please let me know your thoughts!

**Comment by bminer** [comment]
@mitchellh - Would you kindly add me as a contributor to this repo? I see that it is currently unmaintained.  It would be nice to start accepting relevant PRs from the community, even if you think this specific one should be rejected or revised.

**Comment by mitchellh** [comment]
Hey @bminer I'd definitely be open to this. I apologize, I probably don't have time to maintain this properly and unfortunately my urgency is usually selfishly driven my the needs of myself or my company (all our products use this library).

If anyone is interested in helping out please reach out to me. My only request is backwards compatibility is always 100% preserved and that we maintain strong test coverage. I've had success with my other projects bringing on maintainers and keeping in dialog with them if they have any questions too (I'm quick at email). 😄 

I'll take a look at this PR today or tomorrow though!

**Comment by mitchellh** [comment]
This looks good as-is. Thank yoU!

**Comment by bminer** [comment]
Thank you, good sir!  Thanks for checking in!

**Comment by mitchellh** [comment]
No problem, I ended up triaging, merging, and adding some new improvements/fixes as well. That takes care of all the low hanging fruit. There are some PRs open that need tests, some that I think aren't straightforward "yes" answers, etc.

**Pull request merged**
