### PR TITLE
Add decode_hook for time.Time

### PR DESCRIPTION
**Pull request by hori-ryota**

### CODE REVIEW

**Comment by kenneth488** [comment]
+1. Lets get it in if it works.

**Comment by kenneth488** [comment]
Lets get this merged please. Good work hori-ryota.

**Comment by hori-ryota** [comment]
@mitchellh Would you be able to review this?

**Comment by davidknaack** [comment]
It would be nice if the time format could be specified in the config.

**Comment by mitchellh** [comment]
Looks great. Sorry this took so long to merge!

@davidknaack that is effectively what happens here since you configure the hooks in the config and the hook itself takes a layout.

**Pull request merged**
