### PR TITLE
Send reflect.Type instead of reflect.Kind to hook functions

### PR DESCRIPTION
**Pull request by hectorj**
For structs, reflect.Kind is not enough : it doesn't let us know which kind of struct is expected.
With reflect.Type we get more information about src and dest.

It allows for example in the hook to do something like this :
```
if to == reflect.TypeOf(time.Time{}) {
  data = time.Parse([...])
}
```

### CODE REVIEW

**Comment by mitchellh** [comment]
This would break backwards compatibility so we can't do this. But perhaps we can keep backwards compatibility and do something fancier. I'm taking a look.

**Comment by hectorj** [comment]
Hmm.. maybe add a second type of hook functions ?

**Comment by mitchellh** [comment]
See my PR, I got it working :)

**Comment by adamthedeveloper** [comment]
Is this still working? I'm still seeing this exact error occurring. My Struct:

`
  type AppOwner struct {
	Id          string
	Name        string
	Email       string
	ApiKey      string
	ApiSecret   string
	CreatedAt   time.Time
  }

  var a AppOwner
`

`
  appData,err := client.HGetAll(a.RedisKey()).Result()
`

Gives me: 
`
  map[ApiKey:b321b2bf2dfe53e6dbb3c91202f95a5c ApiSecret:c15c447397b3b932a03ec1d903659a68 CreatedAt:2017-10-21 05:57:53.053720785 +0000 UTC Id:8fdb4d11-c848-490d-a3b1-0eba17c43c26 Name:Adam Email:adammede@gmail.com]
`

`
  err = mapstructure.Decode(appData, &a)
  if err != nil { return err }
`

I get `'CreatedAt' expected a map, got 'string'`

Any ideas? Sorry about the formatting.

**Pull request closed without merging**
