### PR TITLE
Check for data type before trying to access its composants prevent a panic error in decodeSlice

### PR DESCRIPTION
**Pull request by ugy**
If you tried to decode a map[string]struct into an initiliazed []struct with zeroField set to False, it would `panic: reflect: call of reflect.Value.Index on map Value` as the data type check wouldn't be done.

I just moved the data type check before checking for a nil slice or zeroField flag.

### CODE REVIEW

**Comment by mitchellh** [comment]
Thanks! To truly resolve this I would like to see a unit test case to cover this as well. If you have time, please add that. Otherwise, I can't merge until I have a bit more free time to write it myself.

**Comment by ugy** [comment]
Hi ! I've done the merge to resolve the conflicts with the commits found on your branch, all tests pass everything seems to work well :)

**Comment by primalmotion** [comment]
What's the status of this one? produces some annoying panics on some user inputs :/

**Comment by mitchellh** [comment]
Merged and fixed. Sorry I couldn't keep authorship here, due to merge conflicts being pretty heavy!

**Pull request closed without merging**
