### PR TITLE
Support to omitempty

### PR DESCRIPTION
**Pull request by perenecabuto**
Add support to omitempty anotation in order to not add map keys with empty values

### CODE REVIEW

**Comment by geoah** [comment]
@perenecabuto thanks for this - works wonderfully!
@mitchellh are they any plans on getting this merged or any reasons not to?

**Comment by xcaptain** [comment]
Need this feature, hope to get merged.

**Comment by wjh000123** [comment]
@mitchellh Hi, are there any plan on getting this merged?

**Comment by perenecabuto** [comment]
@mitchellh I think it is already merged. Probably it only need to be released

**Comment by estebangarcia** [comment]
It would be great if this gets merged!

**Comment by cweerasooriya** [comment]
Great feature. 💯
Is this getting merged anytime soon?

**Comment by hsyed** [comment]
could this be included ?

**Comment by tdakkota** [comment]
Why haven't merged it yet?

**Comment by ideruga** [comment]
Is it possible to merge this?

**Comment by kmanco** [comment]
Can you merge this?

**Comment by soluchok** [comment]
@mitchellh Is this repo maintainable by someone?

**Comment by Dragomir-Ivanov** [comment]
@mitchellh this merge appreciated!

**Comment by crlssn** [comment]
I would like to see this merged as well!

**Pull request merged**
